// TEMP DEMO: Mock data for development/testing only
// In production, all data comes from real API endpoints
// This is kept as a fallback for when VITE_QUIZ_API_URL is not configured

export const mockAssessments = [
  {
    id: "a-python-fundamentals",
    title: "Python Fundamentals",
    description: "Core language features, data types, and OOP basics.",
    module_id: "mod-python-basics",
    question_count: 10,
    topics: ["Data types", "Control flow", "Functions", "OOP basics"],
    status: "not_started", // "not_started" | "in_progress" | "completed"
    last_score: null,
  },
  {
    id: "a-javascript-fundamentals",
    title: "JavaScript Fundamentals",
    description: "Core JavaScript concepts, functions, arrays, and objects.",
    module_id: "mod-javascript-basics",
    question_count: 15,
    topics: ["Variables", "Functions", "Arrays", "DOM basics"],
    status: "completed",
    last_score: 87,
  },
  {
    id: "a-sql-database-basics",
    title: "SQL & Database Basics",
    description: "Fundamentals of relational databases, SQL queries, and normalization.",
    module_id: "mod-sql-basics",
    question_count: 15,
    topics: ["SQL queries", "Joins", "Keys", "Normalization"],
    status: "not_started",
    last_score: null,
  },
  {
    id: "a-machine-learning",
    title: "Machine Learning Basics",
    description: "Core machine learning concepts, model training, and evaluation.",
    module_id: "mod-machine-learning",
    question_count: 15,
    topics: ["Supervised learning", "Model evaluation", "Algorithms", "Overfitting"],
    status: "not_started",
    last_score: null,
  },
];

// Exact structure as provided by the backend team.
export const mockQuestions = {
  "a-python-fundamentals": [
    {
      id: "q-546b29e3",
      sequence_number: 1,
      question_text: "Which of the following Python data types is immutable?",
      question_type: "MCQ",
      options: {
        a: "list",
        b: "dictionary",
        c: "tuple",
        d: "set",
      },
    },
    {
      id: "q-a453ae76",
      sequence_number: 2,
      question_text: "What is true about Python dictionaries?",
      question_type: "MCQ",
      options: {
        a: "Keys must be mutable objects",
        b: "Order of items is guaranteed since Python 3.6",
        c: "They can contain duplicate keys",
        d: "Values are required to be unique",
      },
    },
    {
      id: "q-018352b5",
      sequence_number: 3,
      question_text: "The Singleton design pattern primarily ensures that:",
      question_type: "MCQ",
      options: {
        a: "Only one instance of a class can be created",
        b: "Objects are created without using a constructor",
        c: "All subclasses share the same state",
        d: "Methods are executed in a single thread",
      },
    },
    {
      id: "q-d612fc9e",
      sequence_number: 4,
      question_text:
        "Which design pattern is best suited for creating families of related objects without specifying their concrete classes?",
      question_type: "MCQ",
      options: {
        a: "Builder",
        b: "Factory Method",
        c: "Abstract Factory",
        d: "Prototype",
      },
    },
    {
      id: "q-967be8ff",
      sequence_number: 5,
      question_text: "In Python, the else clause of a while loop executes when:",
      question_type: "MCQ",
      options: {
        a: "The loop condition becomes false",
        b: "A break statement is encountered",
        c: "An exception is raised inside the loop",
        d: "The loop runs exactly once",
      },
    },
    {
      id: "q-f7cb8a75",
      sequence_number: 6,
      question_text:
        "Which loop construct can iterate over a sequence while also providing the index without using the enumerate function?",
      question_type: "MCQ",
      options: {
        a: "for item in sequence",
        b: "while sequence",
        c: "for i in range(len(sequence))",
        d: "for i, item in enumerate(sequence)",
      },
    },
    {
      id: "q-d18a5635",
      sequence_number: 7,
      question_text: "Which statement about method overriding in Python classes is correct?",
      question_type: "MCQ",
      options: {
        a: "The overriding method must have the same name but can have a different number of parameters",
        b: "The overriding method must be declared with the same signature as the method in the base class",
        c: "Method overriding works only for static methods",
        d: "Python does not support method overriding",
      },
    },
    {
      id: "q-d10ea9f0",
      sequence_number: 8,
      question_text: "What is the purpose of the __init__ method in a Python class?",
      question_type: "MCQ",
      options: {
        a: "To create a new class object",
        b: "To initialize instance attributes when an object is created",
        c: "To define a class-level constant",
        d: "To delete an instance when it goes out of scope",
      },
    },
    {
      id: "q-63c626c8",
      sequence_number: 9,
      question_text: "True or False: In Python, functions are first class objects.",
      question_type: "MCQ",
      options: {
        a: "True",
        b: "False",
      },
    },
    {
      id: "q-166bf70e",
      sequence_number: 10,
      question_text: "Which of the following are built-in mutable data types in Python?",
      question_type: "MCQ",
      options: {
        a: "list",
        b: "tuple",
        c: "dict",
        d: "frozenset",
      },
    },
    {
      id: "q-7b2c8d11",
      sequence_number: 11,
      question_text: "Which built-in function returns the number of items in a collection?",
      question_type: "MCQ",
      options: {
        a: "count()",
        b: "size()",
        c: "len()",
        d: "length()",
      },
    },
    {
      id: "q-92f41ac3",
      sequence_number: 12,
      question_text: "Which of the following are mutable Python data types? (Select all that apply)",
      question_type: "MSQ",
      options: {
        a: "list",
        b: "tuple",
        c: "dictionary",
        d: "set",
      },
    },
    {
      id: "q-c84de732",
      sequence_number: 13,
      question_text: "Which of the following are valid ways to create a Python dictionary? (Select all that apply)",
      question_type: "MSQ",
      options: {
        a: "{}",
        b: "dict()",
        c: "[]",
        d: "{'a': 1}",
      },
    },
    {
      id: "q-e31abf90",
      sequence_number: 14,
      question_text: "True or False: Python supports multiple inheritance.",
      question_type: "Boolean",
      options: {
        a: "True",
        b: "False",
      },
    },
    {
      id: "q-5fa93d47",
      sequence_number: 15,
      question_text: "Which of the following statements about Python functions are correct? (Select all that apply)",
      question_type: "MSQ",
      options: {
        a: "Functions can be assigned to variables",
        b: "Functions can be passed as arguments to other functions",
        c: "A function can return another function",
        d: "Functions cannot be stored in collections",
      },
    },
  ],
  "a-javascript-fundamentals": [
    {
      id: "js-q1",
      sequence_number: 1,
      question_text: "Which keyword is used to declare a block-scoped variable in JavaScript?",
      question_type: "MCQ",
      options: {
        a: "var",
        b: "let",
        c: "define",
        d: "constvar",
      },
    },
    {
      id: "js-q2",
      sequence_number: 2,
      question_text: "What is the result of typeof [] ?",
      question_type: "MCQ",
      options: {
        a: "array",
        b: "object",
        c: "list",
        d: "undefined",
      },
    },
    {
      id: "js-q3",
      sequence_number: 3,
      question_text: "Which method adds an element to the end of an array?",
      question_type: "MCQ",
      options: {
        a: "push()",
        b: "append()",
        c: "add()",
        d: "insert()",
      },
    },
    {
      id: "js-q4",
      sequence_number: 4,
      question_text: "Which symbol is used for strict equality comparison?",
      question_type: "MCQ",
      options: {
        a: "==",
        b: "=",
        c: "===",
        d: "!=",
      },
    },
    {
      id: "js-q5",
      sequence_number: 5,
      question_text: "What does DOM stand for?",
      question_type: "MCQ",
      options: {
        a: "Document Object Model",
        b: "Data Object Manager",
        c: "Document Output Method",
        d: "Dynamic Object Mapping",
      },
    },
    {
      id: "js-q6",
      sequence_number: 6,
      question_text: "Which of the following are primitive data types in JavaScript? (Select all that apply)",
      question_type: "MSQ",
      options: {
        a: "string",
        b: "number",
        c: "boolean",
        d: "object",
      },
    },
    {
      id: "js-q7",
      sequence_number: 7,
      question_text: "Which method converts a JSON string into a JavaScript object?",
      question_type: "MCQ",
      options: {
        a: "JSON.stringify()",
        b: "JSON.parse()",
        c: "JSON.convert()",
        d: "JSON.decode()",
      },
    },
    {
      id: "js-q8",
      sequence_number: 8,
      question_text: "True or False: JavaScript supports first-class functions.",
      question_type: "Boolean",
      options: {
        a: "True",
        b: "False",
      },
    },
    {
      id: "js-q9",
      sequence_number: 9,
      question_text: "Which keyword refers to the current object context?",
      question_type: "MCQ",
      options: {
        a: "self",
        b: "current",
        c: "this",
        d: "object",
      },
    },
    {
      id: "js-q10",
      sequence_number: 10,
      question_text: "Which array methods create a new array? (Select all that apply)",
      question_type: "MSQ",
      options: {
        a: "map()",
        b: "filter()",
        c: "push()",
        d: "slice()",
      },
    },
    {
      id: "js-q11",
      sequence_number: 11,
      question_text: "Which loop is commonly used to iterate through array elements?",
      question_type: "MCQ",
      options: {
        a: "for",
        b: "repeat",
        c: "iterate",
        d: "scan",
      },
    },
    {
      id: "js-q12",
      sequence_number: 12,
      question_text: "What is the output type of parseInt('42')?",
      question_type: "MCQ",
      options: {
        a: "string",
        b: "number",
        c: "boolean",
        d: "object",
      },
    },
    {
      id: "js-q13",
      sequence_number: 13,
      question_text: "Which statement is used to stop a loop immediately?",
      question_type: "MCQ",
      options: {
        a: "exit",
        b: "continue",
        c: "stop",
        d: "break",
      },
    },
    {
      id: "js-q14",
      sequence_number: 14,
      question_text: "True or False: const variables can be reassigned after declaration.",
      question_type: "Boolean",
      options: {
        a: "True",
        b: "False",
      },
    },
    {
      id: "js-q15",
      sequence_number: 15,
      question_text: "Which of the following are valid ways to define a function? (Select all that apply)",
      question_type: "MSQ",
      options: {
        a: "function myFunc() {}",
        b: "const myFunc = () => {}",
        c: "let myFunc = function() {}",
        d: "create function myFunc() {}",
      },
    },
  ],

  "a-sql-database-basics": [
    {
      id: "sql-q1",
      sequence_number: 1,
      question_text: "Which SQL statement is used to retrieve data from a table?",
      question_type: "MCQ",
      options: {
        a: "GET",
        b: "SELECT",
        c: "FETCH",
        d: "READ",
      },
    },
    {
      id: "sql-q2",
      sequence_number: 2,
      question_text: "Which clause is used to filter rows in SQL?",
      question_type: "MCQ",
      options: {
        a: "ORDER BY",
        b: "GROUP BY",
        c: "WHERE",
        d: "HAVING",
      },
    },
    {
      id: "sql-q3",
      sequence_number: 3,
      question_text: "What is a primary key?",
      question_type: "MCQ",
      options: {
        a: "A column that uniquely identifies a row",
        b: "A column used only for sorting",
        c: "A duplicate value field",
        d: "A temporary column",
      },
    },
    {
      id: "sql-q4",
      sequence_number: 4,
      question_text: "Which SQL command is used to add new records?",
      question_type: "MCQ",
      options: {
        a: "CREATE",
        b: "INSERT",
        c: "UPDATE",
        d: "ALTER",
      },
    },
    {
      id: "sql-q5",
      sequence_number: 5,
      question_text: "Which join returns only matching rows from both tables?",
      question_type: "MCQ",
      options: {
        a: "LEFT JOIN",
        b: "RIGHT JOIN",
        c: "INNER JOIN",
        d: "FULL JOIN",
      },
    },
    {
      id: "sql-q6",
      sequence_number: 6,
      question_text: "Which of the following are aggregate functions? (Select all that apply)",
      question_type: "MSQ",
      options: {
        a: "COUNT()",
        b: "SUM()",
        c: "AVG()",
        d: "ORDER BY",
      },
    },
    {
      id: "sql-q7",
      sequence_number: 7,
      question_text: "What does SQL stand for?",
      question_type: "MCQ",
      options: {
        a: "Structured Query Language",
        b: "Simple Query Language",
        c: "System Query Logic",
        d: "Sequential Query Language",
      },
    },
    {
      id: "sql-q8",
      sequence_number: 8,
      question_text: "True or False: A table can have only one primary key.",
      question_type: "Boolean",
      options: {
        a: "True",
        b: "False",
      },
    },
    {
      id: "sql-q9",
      sequence_number: 9,
      question_text: "Which SQL statement modifies existing records?",
      question_type: "MCQ",
      options: {
        a: "ALTER",
        b: "MODIFY",
        c: "UPDATE",
        d: "CHANGE",
      },
    },
    {
      id: "sql-q10",
      sequence_number: 10,
      question_text: "Which clause is used to sort query results?",
      question_type: "MCQ",
      options: {
        a: "SORT BY",
        b: "ORDER BY",
        c: "GROUP BY",
        d: "ARRANGE BY",
      },
    },
    {
      id: "sql-q11",
      sequence_number: 11,
      question_text: "Which of the following constraints can enforce uniqueness? (Select all that apply)",
      question_type: "MSQ",
      options: {
        a: "PRIMARY KEY",
        b: "UNIQUE",
        c: "FOREIGN KEY",
        d: "CHECK",
      },
    },
    {
      id: "sql-q12",
      sequence_number: 12,
      question_text: "Which command removes all rows but keeps the table structure?",
      question_type: "MCQ",
      options: {
        a: "DELETE",
        b: "DROP",
        c: "TRUNCATE",
        d: "REMOVE",
      },
    },
    {
      id: "sql-q13",
      sequence_number: 13,
      question_text: "What is database normalization primarily used for?",
      question_type: "MCQ",
      options: {
        a: "Increasing redundancy",
        b: "Reducing data duplication",
        c: "Encrypting data",
        d: "Improving UI design",
      },
    },
    {
      id: "sql-q14",
      sequence_number: 14,
      question_text: "True or False: A FOREIGN KEY can reference a PRIMARY KEY in another table.",
      question_type: "Boolean",
      options: {
        a: "True",
        b: "False",
      },
    },
    {
      id: "sql-q15",
      sequence_number: 15,
      question_text: "Which SQL clauses can be used with aggregate functions? (Select all that apply)",
      question_type: "MSQ",
      options: {
        a: "GROUP BY",
        b: "HAVING",
        c: "WHERE",
        d: "ORDER BY",
      },
    },
  ],
  "a-machine-learning": [
    {
      id: "ml-q1",
      sequence_number: 1,
      question_text: "Which type of machine learning uses labeled training data?",
      question_type: "MCQ",
      options: {
        a: "Supervised learning",
        b: "Unsupervised learning",
        c: "Reinforcement learning",
        d: "Self-organizing learning",
      },
    },
    {
      id: "ml-q2",
      sequence_number: 2,
      question_text: "Which algorithm is commonly used for classification tasks?",
      question_type: "MCQ",
      options: {
        a: "K-means clustering",
        b: "Linear regression",
        c: "Logistic regression",
        d: "Principal component analysis",
      },
    },
    {
      id: "ml-q3",
      sequence_number: 3,
      question_text: "What does overfitting mean?",
      question_type: "MCQ",
      options: {
        a: "The model performs well on training data but poorly on new data",
        b: "The model has too few parameters to learn patterns",
        c: "The model never updates its weights",
        d: "The dataset has no labels",
      },
    },
    {
      id: "ml-q4",
      sequence_number: 4,
      question_text: "Which metric is useful for evaluating a classification model?",
      question_type: "MCQ",
      options: {
        a: "Accuracy",
        b: "Latency only",
        c: "File size",
        d: "Memory address",
      },
    },
    {
      id: "ml-q5",
      sequence_number: 5,
      question_text: "What is the purpose of a validation set?",
      question_type: "MCQ",
      options: {
        a: "To tune model choices without using the final test set",
        b: "To permanently store production predictions",
        c: "To replace training data",
        d: "To remove all features from a dataset",
      },
    },
    {
      id: "ml-q6",
      sequence_number: 6,
      question_text: "Which of the following are supervised learning tasks? (Select all that apply)",
      question_type: "MSQ",
      options: {
        a: "Classification",
        b: "Regression",
        c: "Clustering",
        d: "Dimensionality reduction only",
      },
    },
    {
      id: "ml-q7",
      sequence_number: 7,
      question_text: "Which algorithm groups similar data points without labels?",
      question_type: "MCQ",
      options: {
        a: "Decision tree",
        b: "K-means clustering",
        c: "Logistic regression",
        d: "Naive Bayes",
      },
    },
    {
      id: "ml-q8",
      sequence_number: 8,
      question_text: "True or False: More training data can often help reduce overfitting.",
      question_type: "Boolean",
      options: {
        a: "True",
        b: "False",
      },
    },
    {
      id: "ml-q9",
      sequence_number: 9,
      question_text: "What is a feature in a machine learning dataset?",
      question_type: "MCQ",
      options: {
        a: "An input variable used by the model",
        b: "The final deployed application",
        c: "A database password",
        d: "Only the model output",
      },
    },
    {
      id: "ml-q10",
      sequence_number: 10,
      question_text: "Which technique can help reduce overfitting?",
      question_type: "MCQ",
      options: {
        a: "Regularization",
        b: "Removing validation data",
        c: "Training forever without testing",
        d: "Using only one example",
      },
    },
    {
      id: "ml-q11",
      sequence_number: 11,
      question_text: "Which metric balances precision and recall?",
      question_type: "MCQ",
      options: {
        a: "F1 score",
        b: "Mean only",
        c: "Dataset size",
        d: "Epoch count",
      },
    },
    {
      id: "ml-q12",
      sequence_number: 12,
      question_text: "Which of these are common model evaluation metrics? (Select all that apply)",
      question_type: "MSQ",
      options: {
        a: "Precision",
        b: "Recall",
        c: "F1 score",
        d: "Theme color",
      },
    },
    {
      id: "ml-q13",
      sequence_number: 13,
      question_text: "What is the target variable in supervised learning?",
      question_type: "MCQ",
      options: {
        a: "The value the model is trained to predict",
        b: "A random unused column",
        c: "The file name of the dataset",
        d: "The number of CPU cores",
      },
    },
    {
      id: "ml-q14",
      sequence_number: 14,
      question_text: "True or False: A test set should be used to estimate final model performance.",
      question_type: "Boolean",
      options: {
        a: "True",
        b: "False",
      },
    },
    {
      id: "ml-q15",
      sequence_number: 15,
      question_text: "Which algorithms can be used for classification? (Select all that apply)",
      question_type: "MSQ",
      options: {
        a: "Decision tree",
        b: "Logistic regression",
        c: "Support vector machine",
        d: "K-means clustering only",
      },
    },
  ],
};







